import React from 'react'
import styled from "styled-components";

function PositionSticky() {
    return <div>
        <TopNavbar>This is the top navbar</TopNavbar>
        <Content>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean lacus libero, porta at vehicula sed, bibendum eget velit. Sed non enim nec magna facilisis placerat. Vivamus sit amet scelerisque tellus. Aliquam viverra volutpat euismod. Vestibulum et sapien ullamcorper, tincidunt velit pretium, tristique ante. Proin nec rhoncus sem, sit amet semper nisi. Vivamus nec venenatis nunc, et egestas mauris. Sed id risus dapibus, cursus sem vitae, sagittis magna. Phasellus elit elit, auctor porttitor pharetra et, consectetur in leo. Maecenas at massa ut neque rhoncus dictum eget a leo. Maecenas risus urna, cursus at ex ac, suscipit vulputate erat. Fusce id lorem dictum, congue lacus id, condimentum lectus.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean lacus libero, porta at vehicula sed, bibendum eget velit. Sed non enim nec magna facilisis placerat. Vivamus sit amet scelerisque tellus. Aliquam viverra volutpat euismod. Vestibulum et sapien ullamcorper, tincidunt velit pretium, tristique ante. Proin nec rhoncus sem, sit amet semper nisi. Vivamus nec venenatis nunc, et egestas mauris. Sed id risus dapibus, cursus sem vitae, sagittis magna. Phasellus elit elit, auctor porttitor pharetra et, consectetur in leo. Maecenas at massa ut neque rhoncus dictum eget a leo. Maecenas risus urna, cursus at ex ac, suscipit vulputate erat. Fusce id lorem dictum, congue lacus id, condimentum lectus.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean lacus libero, porta at vehicula sed, bibendum eget velit. Sed non enim nec magna facilisis placerat. Vivamus sit amet scelerisque tellus. Aliquam viverra volutpat euismod. Vestibulum et sapien ullamcorper, tincidunt velit pretium, tristique ante. Proin nec rhoncus sem, sit amet semper nisi. Vivamus nec venenatis nunc, et egestas mauris. Sed id risus dapibus, cursus sem vitae, sagittis magna. Phasellus elit elit, auctor porttitor pharetra et, consectetur in leo. Maecenas at massa ut neque rhoncus dictum eget a leo. Maecenas risus urna, cursus at ex ac, suscipit vulputate erat. Fusce id lorem dictum, congue lacus id, condimentum lectus.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean lacus libero, porta at vehicula sed, bibendum eget velit. Sed non enim nec magna facilisis placerat. Vivamus sit amet scelerisque tellus. Aliquam viverra volutpat euismod. Vestibulum et sapien ullamcorper, tincidunt velit pretium, tristique ante. Proin nec rhoncus sem, sit amet semper nisi. Vivamus nec venenatis nunc, et egestas mauris. Sed id risus dapibus, cursus sem vitae, sagittis magna. Phasellus elit elit, auctor porttitor pharetra et, consectetur in leo. Maecenas at massa ut neque rhoncus dictum eget a leo. Maecenas risus urna, cursus at ex ac, suscipit vulputate erat. Fusce id lorem dictum, congue lacus id, condimentum lectus.</p>
            <p>Nullam pulvinar diam sed enim mattis, et pulvinar tellus ornare. Sed mattis neque eget elementum laoreet. Curabitur dignissim libero nec dolor porta, vel maximus metus dignissim. Aliquam bibendum tincidunt lobortis. Fusce vulputate leo et arcu molestie, id vehicula arcu ullamcorper. Etiam hendrerit turpis a vestibulum dictum. Aliquam pellentesque pharetra maximus. Quisque quis libero in velit vestibulum dictum sed et ipsum. Mauris ultrices in massa quis gravida. Cras eget ligula orci. Ut ut lorem nec justo eleifend viverra. Nullam sed suscipit ante.</p>
            <p>Nullam pulvinar diam sed enim mattis, et pulvinar tellus ornare. Sed mattis neque eget elementum laoreet. Curabitur dignissim libero nec dolor porta, vel maximus metus dignissim. Aliquam bibendum tincidunt lobortis. Fusce vulputate leo et arcu molestie, id vehicula arcu ullamcorper. Etiam hendrerit turpis a vestibulum dictum. Aliquam pellentesque pharetra maximus. Quisque quis libero in velit vestibulum dictum sed et ipsum. Mauris ultrices in massa quis gravida. Cras eget ligula orci. Ut ut lorem nec justo eleifend viverra. Nullam sed suscipit ante.</p>
            <p>Nullam pulvinar diam sed enim mattis, et pulvinar tellus ornare. Sed mattis neque eget elementum laoreet. Curabitur dignissim libero nec dolor porta, vel maximus metus dignissim. Aliquam bibendum tincidunt lobortis. Fusce vulputate leo et arcu molestie, id vehicula arcu ullamcorper. Etiam hendrerit turpis a vestibulum dictum. Aliquam pellentesque pharetra maximus. Quisque quis libero in velit vestibulum dictum sed et ipsum. Mauris ultrices in massa quis gravida. Cras eget ligula orci. Ut ut lorem nec justo eleifend viverra. Nullam sed suscipit ante.</p>
            <p>Nullam pulvinar diam sed enim mattis, et pulvinar tellus ornare. Sed mattis neque eget elementum laoreet. Curabitur dignissim libero nec dolor porta, vel maximus metus dignissim. Aliquam bibendum tincidunt lobortis. Fusce vulputate leo et arcu molestie, id vehicula arcu ullamcorper. Etiam hendrerit turpis a vestibulum dictum. Aliquam pellentesque pharetra maximus. Quisque quis libero in velit vestibulum dictum sed et ipsum. Mauris ultrices in massa quis gravida. Cras eget ligula orci. Ut ut lorem nec justo eleifend viverra. Nullam sed suscipit ante.</p>
            <p>In hac habitasse platea dictumst. Sed lacinia ante commodo, consequat nisl vel, elementum nulla. Aliquam finibus ullamcorper lorem, sed convallis leo. Aliquam auctor urna vel risus convallis ullamcorper. Maecenas maximus elementum imperdiet. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec maximus metus eu velit suscipit, at convallis est pellentesque. Cras sit amet augue suscipit, tristique ligula nec, vehicula tellus. Donec faucibus mi nec tellus accumsan, eu feugiat nunc tincidunt. Fusce id auctor dolor.</p>
            <p>In hac habitasse platea dictumst. Sed lacinia ante commodo, consequat nisl vel, elementum nulla. Aliquam finibus ullamcorper lorem, sed convallis leo. Aliquam auctor urna vel risus convallis ullamcorper. Maecenas maximus elementum imperdiet. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec maximus metus eu velit suscipit, at convallis est pellentesque. Cras sit amet augue suscipit, tristique ligula nec, vehicula tellus. Donec faucibus mi nec tellus accumsan, eu feugiat nunc tincidunt. Fusce id auctor dolor.</p>
            <p>In hac habitasse platea dictumst. Sed lacinia ante commodo, consequat nisl vel, elementum nulla. Aliquam finibus ullamcorper lorem, sed convallis leo. Aliquam auctor urna vel risus convallis ullamcorper. Maecenas maximus elementum imperdiet. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec maximus metus eu velit suscipit, at convallis est pellentesque. Cras sit amet augue suscipit, tristique ligula nec, vehicula tellus. Donec faucibus mi nec tellus accumsan, eu feugiat nunc tincidunt. Fusce id auctor dolor.</p>
            <p>In hac habitasse platea dictumst. Sed lacinia ante commodo, consequat nisl vel, elementum nulla. Aliquam finibus ullamcorper lorem, sed convallis leo. Aliquam auctor urna vel risus convallis ullamcorper. Maecenas maximus elementum imperdiet. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec maximus metus eu velit suscipit, at convallis est pellentesque. Cras sit amet augue suscipit, tristique ligula nec, vehicula tellus. Donec faucibus mi nec tellus accumsan, eu feugiat nunc tincidunt. Fusce id auctor dolor.</p>
            <p>Duis eget magna sed purus vehicula mollis. Maecenas eget metus lacus. Duis sapien diam, viverra at erat vitae, ullamcorper tristique tortor. Nullam varius justo sit amet ante sagittis malesuada. Quisque vitae finibus dui. In ullamcorper consequat velit mollis interdum. Pellentesque at fermentum sapien, id aliquet purus. Integer tempus pulvinar justo. Sed congue, odio interdum ultrices ultricies, massa odio euismod urna, id finibus neque diam ut risus. Sed metus mi, tristique sed tempor vel, suscipit sed lacus. Mauris suscipit nec odio at dapibus. Suspendisse eros nibh, auctor id tristique aliquam, efficitur quis magna.</p>
            <p>Duis eget magna sed purus vehicula mollis. Maecenas eget metus lacus. Duis sapien diam, viverra at erat vitae, ullamcorper tristique tortor. Nullam varius justo sit amet ante sagittis malesuada. Quisque vitae finibus dui. In ullamcorper consequat velit mollis interdum. Pellentesque at fermentum sapien, id aliquet purus. Integer tempus pulvinar justo. Sed congue, odio interdum ultrices ultricies, massa odio euismod urna, id finibus neque diam ut risus. Sed metus mi, tristique sed tempor vel, suscipit sed lacus. Mauris suscipit nec odio at dapibus. Suspendisse eros nibh, auctor id tristique aliquam, efficitur quis magna.</p>
            <p>Duis eget magna sed purus vehicula mollis. Maecenas eget metus lacus. Duis sapien diam, viverra at erat vitae, ullamcorper tristique tortor. Nullam varius justo sit amet ante sagittis malesuada. Quisque vitae finibus dui. In ullamcorper consequat velit mollis interdum. Pellentesque at fermentum sapien, id aliquet purus. Integer tempus pulvinar justo. Sed congue, odio interdum ultrices ultricies, massa odio euismod urna, id finibus neque diam ut risus. Sed metus mi, tristique sed tempor vel, suscipit sed lacus. Mauris suscipit nec odio at dapibus. Suspendisse eros nibh, auctor id tristique aliquam, efficitur quis magna.</p>
            <p>Duis eget magna sed purus vehicula mollis. Maecenas eget metus lacus. Duis sapien diam, viverra at erat vitae, ullamcorper tristique tortor. Nullam varius justo sit amet ante sagittis malesuada. Quisque vitae finibus dui. In ullamcorper consequat velit mollis interdum. Pellentesque at fermentum sapien, id aliquet purus. Integer tempus pulvinar justo. Sed congue, odio interdum ultrices ultricies, massa odio euismod urna, id finibus neque diam ut risus. Sed metus mi, tristique sed tempor vel, suscipit sed lacus. Mauris suscipit nec odio at dapibus. Suspendisse eros nibh, auctor id tristique aliquam, efficitur quis magna.</p>
        </Content>
    </div>
}

const TopNavbar = styled.div`
  color: white;
  background: blue;
  position: sticky;
  top: 0;
  height: 100px;
  width: 100%;
`
const Content = styled.div`
  color: white;
  background: green;
  height: 100vh;
  width: 100%
`

export default PositionSticky